# Generated by Django 2.2.3 on 2019-07-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spamword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_id', models.CharField(blank=True, max_length=255, verbose_name='Secret ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=30, verbose_name='Author')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_highlighted', models.TextField(blank=True, verbose_name='Highlighted Content')),
                ('lexer', models.CharField(default='text', max_length=30, verbose_name='Lexer')),
                ('published', models.DateTimeField(blank=True, db_index=True, verbose_name='Published')),
                ('expires', models.DateTimeField(blank=True, db_index=True, verbose_name='Expires')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='pastebin.Snippet')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
