# Generated by Django 2.2.16 on 2020-09-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest_version', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestversion',
            name='name',
            field=models.CharField(default='Geany', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
